# Workflow (no indentation required for naming the workflow)
# Should  Have a Name
name: Hello
# on tell when the workflow should run (give indentation by tab)
on:
  workflow_dispatch: 
# Jobs
# Should be inside the workflow (tells what the workflow do)
# there can be one or more jobs, hence we write jobs, jobs is an object so we need indentation
jobs:
  #1st job (give indentation)
  say-hello:
    #create an Ephermal Container with Ubuntu running
    runs-on: ubuntu-latest
    #That ephermal container will have steps to execute, hence name those steps and use run: run has the commnd
# Steps
# Should be inside the Jobs
    
    steps:
     - name: say hello to everyone
       run: echo "Hello Dosto"
# Actions
# Should be inside the steps
