name: Auto Linter

on:
  push:
    paths:
      - "**/*.py"
  pull_request:
    paths:
      - "**/*.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Linter
        run: ruff check .
