# What is the goal of your workflow
# Goal: whenever a chges happen in any python file 
# linter will check format, syntax, indentation is correct or not

name: Auto Linter

on:
  push:
    paths:
      - "**/*.py"

jobs:
  code-linting:
    runs-on: ubuntu-latest
    steps:
      # Clone the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install linter
      - name: Install Ruff
        run: pip install ruff

      # Run linter
      - name: Run Ruff check
        run: ruff check .
